package model;
// Generated 28/05/2024 23:20:30 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private BigDecimal peso;
     private Set realizas = new HashSet(0);

    public Avaliacao() {
    }

	
    public Avaliacao(String descricao, BigDecimal peso) {
        this.descricao = descricao;
        this.peso = peso;
    }
    public Avaliacao(String descricao, BigDecimal peso, Set realizas) {
       this.descricao = descricao;
       this.peso = peso;
       this.realizas = realizas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }




}


