package model;
// Generated 28/05/2024 23:20:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


      private Integer id;
    private String nome;
    private Set<Disciplina> disciplinas = new HashSet<>();
    private Set<Estudante> estudantes = new HashSet<>();
    private Set<Turma> turmas = new HashSet<>();

    public Curso() {
    }

	
    public Curso(String nome) {
        this.nome = nome;
    }
    public Curso(String nome, Set disciplinas, Set estudantes, Set turmas) {
       this.nome = nome;
       this.disciplinas = disciplinas;
       this.estudantes = estudantes;
       this.turmas = turmas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set disciplinas) {
        this.disciplinas = disciplinas;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }
    public Set getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set turmas) {
        this.turmas = turmas;
    }

    @Override
    public String toString() {
        return "Curso{" + "id=" + id + ", nome=" + nome + '}';
    }




}


