package model;
// Generated 28/05/2024 23:20:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Disciplina generated by hbm2java
 */
public class Disciplina  implements java.io.Serializable {


     private Integer id;
     private Curso curso;
     private String nome;
     private int chs;
     private int credito;
     private Set realizas = new HashSet(0);

    public Disciplina() {
    }

	
    public Disciplina(Curso curso, String nome, int chs, int credito) {
        this.curso = curso;
        this.nome = nome;
        this.chs = chs;
        this.credito = credito;
    }
    public Disciplina(Curso curso, String nome, int chs, int credito, Set realizas) {
       this.curso = curso;
       this.nome = nome;
       this.chs = chs;
       this.credito = credito;
       this.realizas = realizas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getChs() {
        return this.chs;
    }
    
    public void setChs(int chs) {
        this.chs = chs;
    }
    public int getCredito() {
        return this.credito;
    }
    
    public void setCredito(int credito) {
        this.credito = credito;
    }
    public Set getRealizas() {
        return this.realizas;
    }
    
    public void setRealizas(Set realizas) {
        this.realizas = realizas;
    }




}


