package model;
// Generated 28/05/2024 23:20:30 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Realiza generated by hbm2java
 */
public class Realiza  implements java.io.Serializable {


     private int idEstudante;
     private Avaliacao avaliacao;
     private Disciplina disciplina;
     private Estudante estudante;
     private BigDecimal nota;

    public Realiza() {
    }

    public Realiza(Avaliacao avaliacao, Disciplina disciplina, Estudante estudante, BigDecimal nota) {
       this.avaliacao = avaliacao;
       this.disciplina = disciplina;
       this.estudante = estudante;
       this.nota = nota;
    }
   
    public int getIdEstudante() {
        return this.idEstudante;
    }
    
    public void setIdEstudante(int idEstudante) {
        this.idEstudante = idEstudante;
    }
    public Avaliacao getAvaliacao() {
        return this.avaliacao;
    }
    
    public void setAvaliacao(Avaliacao avaliacao) {
        this.avaliacao = avaliacao;
    }
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }
    public Estudante getEstudante() {
        return this.estudante;
    }
    
    public void setEstudante(Estudante estudante) {
        this.estudante = estudante;
    }
    public BigDecimal getNota() {
        return this.nota;
    }
    
    public void setNota(BigDecimal nota) {
        this.nota = nota;
    }




}


