package model;
// Generated 28/05/2024 23:20:30 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Turma generated by hbm2java
 */
public class Turma  implements java.io.Serializable {


     private Integer id;
     private Curso curso;
     private String descricao;
     private Set estudantes = new HashSet(0);

    public Turma() {
    }

	
    public Turma(Curso curso, String descricao) {
        this.curso = curso;
        this.descricao = descricao;
    }
    public Turma(Curso curso, String descricao, Set estudantes) {
       this.curso = curso;
       this.descricao = descricao;
       this.estudantes = estudantes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getEstudantes() {
        return this.estudantes;
    }
    
    public void setEstudantes(Set estudantes) {
        this.estudantes = estudantes;
    }




}


